[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <you@example.com>"]
description = "A fun game where you guess what number the computer has chosen."
license = "MIT"

[dependencies]
